### PR TITLE
Fix issues mentioned in PED

### LINKED ISSUE #110: Students with identical names are stored in the same key of treemap
Students with identical names are stored in the same key in the TreeMap due to the Comparator function

Steps to reproduce:
- Add 2 "John Doe" students and add studio. Then mark student at index 1 as present/absent.

### PR DESCRIPTION
**Pull request by rycs2812**
- Make Student, Task, Lesson implement Comparable
  - Remove comparators from all TreeMap/TreeSet instantiations
- Fix bug with LessonCard not displaying student's edited name (in default view)
- Disallow marks greater than total mark of assessment in grade command usage
- Add checks to setStudent method in LessonAttendance/LessonNotes/StudioParticipation

Fixes #110, #132, #147, #150, #151

### CODE REVIEW

File: src/main/java/jarvis/logic/commands/AddConsultCommand.java [hunk 1]
```diff
@@ -72,7 +72,14 @@ public CommandResult execute(Model model) throws CommandException {
...
 
-        Set<Student> studentSet = new HashSet<>();
+        Set<Student> studentSet = new TreeSet<>((s1, s2) -> {
+            int result = s1.getName().toString().toLowerCase().compareTo(s2.getName().toString().toLowerCase());
+            if (result == 0) {
+                return s1.getMatricNum().toString().compareTo(s2.getMatricNum().toString());
+            }
+            return result;
+        });
+
```
Comment (fongyj) [inline src/main/java/jarvis/logic/commands/AddConsultCommand.java:82]: I think the code to compare between students is abit repetitive across the 5 changed files. Maybe we can shift this implementation to the student class? 

So I am thinking the `Student` class can `implement Comparable<Student>` then shift this comparison to the `compareTo` method. Then there would be no need to specify an explicit Comparator and the comparison between students can be placed in the student class.

**Review by fongyj — CHANGES_REQUESTED** [review]

**Review by fongyj — APPROVED** [review]
LGTM
